os:
  - windows
  - linux
  - osx
language: rust
sudo: required
rust:
  - stable
  - beta
env:
  - FEATURES_FLAG=""
  - FEATURES_FLAG="--features nifti_images"
script: cargo test $FEATURES_FLAG

dist: bionic
addons:
    apt:
        packages:
            - libssl-dev

# Only run coverage on Linux, Stable Rust and full features
before_script: |
  if [[ "$FEATURES_FLAG" == "--features nifti_images" && "$TRAVIS_RUST_VERSION" == stable && "$TRAVIS_OS_NAME" == linux ]]; then
    cargo install cargo-tarpaulin
  fi

after_success: |
  if [[ "$FEATURES_FLAG" == "--features nifti_images" && "$TRAVIS_RUST_VERSION" == stable && "$TRAVIS_OS_NAME" == linux ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
