os:
  - linux
language: rust
sudo: required
rust:
  - stable
  - beta
env:
  - FEATURES_FLAG=""
  - FEATURES_FLAG="--features nifti_images"
script: cargo test $FEATURES_FLAG

dist: bionic
addons:
    apt:
        packages:
            - libssl-dev

before_script: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
  fi

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    # bash <(curl -s https://codecov.io/bash)
  fi
