[package]
name = "trk-io"
version = "0.12.0"
authors = ["Nil Goyette <nil.goyette@imeka.ca>"]

description = "TrackVis (*.trk) reader and writer"
repository = "https://github.com/imeka/trk-io"
readme = "README.md"
keywords = ["diffusion-mri", "trackvis", "trk"]
categories = ["data-structures", "science"]
license = "BSD-2-Clause"

[features]
nifti_images = ["nifti"]

[dependencies]
byteorder = "1.3"
nalgebra = "0.18"

[dev-dependencies]
docopt = "1.1"
rand = { version = "0.7", features = ["small_rng"] }
tempdir = "0.3"

[dependencies.nifti]
version = "0.8"
features = ["nalgebra_affine", "ndarray_volumes"]
optional = true
