[package]
name = "trk-io"
version = "0.3.8"
authors = ["Nil Goyette <nil.goyette@imeka.ca>"]

description = "TrackVis (*.trk) reader and writer"
repository = "https://github.com/imeka/trk-io"
readme = "README-crates.io.md"
keywords = ["diffusion-mri", "trackvis", "trk"]
categories = ["data-structures", "science"]
license = "BSD-2-Clause"

[features]
use_nifti = ["nifti"]

[dependencies]
byteorder = "1.2"
docopt = "0.8"
nalgebra = "0.13"
tempdir = "0.3"

[dependencies.nifti]
version = "0.4"
features = ["ndarray_volumes"]
optional = true
