[package]
name = "trk-io"
version = "0.1.0"
authors = ["Nil Goyette <nil.goyette@imeka.ca>"]

description = "TrackVis (*.trk) reader and writer"
repository = "https://github.com/imeka/trk-io"
readme = "README-crates.io.md"
keywords = ["diffusion-mri", "trackvis", "trk"]
categories = ["data-structures", "science"]
license = "BSD-2-Clause"

[dependencies]
byteorder = "1.2.1"
docopt = "0.8.1"
nalgebra = "0.13.1"
tempdir = "0.3.5"
