[package]
name = "trk-io"
version = "0.6.1"
authors = ["Nil Goyette <nil.goyette@imeka.ca>"]

description = "TrackVis (*.trk) reader and writer"
repository = "https://github.com/imeka/trk-io"
readme = "README.md"
keywords = ["diffusion-mri", "trackvis", "trk"]
categories = ["data-structures", "science"]
license = "BSD-2-Clause"

[features]
use_nifti = ["nifti"]

[dependencies]
byteorder = "1.2"
nalgebra = "0.15"

[dev-dependencies]
docopt = "1.0"
rand = "0.5"
tempdir = "0.3"

[dependencies.nifti]
version = "0.5"
features = ["ndarray_volumes"]
optional = true
