[package]
name = "trk-io"
version = "0.16.0"
authors = ["Nil Goyette <nil.goyette@imeka.ca>"]

description = "TrackVis (*.trk) reader and writer"
repository = "https://github.com/imeka/trk-io"
readme = "README.md"
keywords = ["diffusion-mri", "trackvis", "trk"]
categories = ["data-structures", "science"]
license = "BSD-2-Clause"
edition = "2018"

[features]
nifti_images = ["nifti"]

[dependencies]
byteorder = "1.3"
nalgebra = "0.23"

[dev-dependencies]
docopt = "1.1"
rand = { version = "0.7", default-features = false, features = ["small_rng"] }
tempfile = "3.1"

[dependencies.nifti]
version = "0.11"
features = ["nalgebra_affine", "ndarray_volumes"]
optional = true
